"""Reply generation (spec stage 6).

"Generate the reply email from quote + quote_line — numbers pulled
programmatically from the record, never retyped or re-generated by the AI, so
what was approved is exactly what sends."

There is no AI in this module and there must never be one. Everything the
customer reads is formatted directly from the stored quote. If the wording
needs to change, it changes here, in a template, under review — not per-send.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from decimal import Decimal
from html import escape

from sqlalchemy.orm import Session

from app.enums import JobType, QuoteStatus
from app.models import Enquiry, Quote

CURRENCY = "£"


class ReplyError(Exception):
    pass


@dataclass
class DraftReply:
    subject: str
    body_text: str
    body_html: str
    to: list[str]

    def as_dict(self) -> dict:
        return {
            "subject": self.subject,
            "body_text": self.body_text,
            "body_html": self.body_html,
            "to": self.to,
        }


def _money(value: Decimal | None) -> str:
    return f"{CURRENCY}{Decimal(value or 0):,.2f}"


def _lead_time_line(quote: Quote) -> str:
    if not quote.lead_time_days:
        return "Lead time: to be confirmed."
    due = date.today() + timedelta(days=quote.lead_time_days)
    return (
        f"Lead time: {quote.lead_time_days} working days from receipt of order "
        f"(approximately {due.strftime('%d %B %Y')})."
    )


def build_reply(db: Session, enquiry: Enquiry, quote: Quote) -> DraftReply:
    """Render the quotation email from the stored record.

    Refuses to render an unapproved quote: the draft that lands in the
    estimator's mailbox must be the thing a human signed off, not a work in
    progress that happened to be current when somebody clicked.
    """
    if quote.status not in (QuoteStatus.APPROVED.value, QuoteStatus.SENT.value):
        raise ReplyError(
            f"Quote {quote.id} is {quote.status}; only an approved quote can be "
            "drafted for sending."
        )
    if not quote.lines:
        raise ReplyError(f"Quote {quote.id} has no lines to quote.")

    customer_name = enquiry.customer.name if enquiry.customer else "Sir or Madam"
    reference = f"Q{quote.id}-{quote.version}"

    subject = f"Quotation {reference}"
    if enquiry.subject:
        subject += f" — re: {enquiry.subject}"

    service_only = all(
        line.part is not None and line.part.job_type == JobType.SERVICE_ONLY.value
        for line in quote.lines
        if line.part is not None
    )

    text_lines = [
        f"Dear {customer_name},",
        "",
        "Thank you for your enquiry. We are pleased to quote as follows.",
        "",
        f"Our reference: {reference}",
    ]
    if enquiry.customer_reference:
        text_lines.append(f"Your reference: {enquiry.customer_reference}")
    text_lines += ["", "-" * 64]

    for line in quote.lines:
        drawing = line.drawing_number or "—"
        revision = f" rev {line.revision}" if line.revision else ""
        text_lines += [
            f"Drawing {drawing}{revision}" + (f" — {line.description}" if line.description else ""),
            f"  Quantity:    {line.quantity}",
            f"  Unit price:  {_money(line.unit_price)}",
            f"  Line total:  {_money(line.line_total)}",
            "",
        ]

    for adjustment in quote.adjustments or []:
        label = adjustment.get("description") or adjustment.get("rule_key", "Adjustment")
        text_lines.append(f"{label}: {_money(Decimal(adjustment['effect']))}")
    if quote.adjustments:
        text_lines.append("")

    text_lines += [
        "-" * 64,
        f"Total (excluding VAT): {_money(quote.quote_value)}",
        "",
        _lead_time_line(quote),
    ]
    if service_only:
        text_lines.append(
            "This quotation is for machining only; material to be supplied by yourselves."
        )
    else:
        text_lines.append("Price includes material.")
    if enquiry.customer is not None and enquiry.customer.requires_cert:
        text_lines.append("Certification will be supplied with the parts.")

    text_lines += [
        "",
        "This quotation is valid for 30 days. Please let us know if anything needs adjusting.",
        "",
        "Kind regards",
    ]

    body_text = "\n".join(text_lines)

    rows = "".join(
        "<tr>"
        f"<td>{escape(line.drawing_number or '—')}"
        f"{escape(' rev ' + line.revision) if line.revision else ''}</td>"
        f"<td>{escape(line.description or '')}</td>"
        f"<td style='text-align:right'>{line.quantity}</td>"
        f"<td style='text-align:right'>{escape(_money(line.unit_price))}</td>"
        f"<td style='text-align:right'>{escape(_money(line.line_total))}</td>"
        "</tr>"
        for line in quote.lines
    )
    adjustment_rows = "".join(
        "<tr>"
        f"<td colspan='4'>{escape(str(a.get('description') or a.get('rule_key', 'Adjustment')))}</td>"
        f"<td style='text-align:right'>{escape(_money(Decimal(a['effect'])))}</td>"
        "</tr>"
        for a in (quote.adjustments or [])
    )

    body_html = f"""\
<p>Dear {escape(customer_name)},</p>
<p>Thank you for your enquiry. We are pleased to quote as follows.</p>
<p>Our reference: <strong>{escape(reference)}</strong>
{
        f"<br>Your reference: {escape(enquiry.customer_reference)}"
        if enquiry.customer_reference
        else ""
    }</p>
<table cellpadding="6" cellspacing="0" border="0" style="border-collapse:collapse">
  <thead>
    <tr style="border-bottom:1px solid #999">
      <th align="left">Drawing</th><th align="left">Description</th>
      <th align="right">Qty</th><th align="right">Unit price</th>
      <th align="right">Line total</th>
    </tr>
  </thead>
  <tbody>{rows}{adjustment_rows}</tbody>
  <tfoot>
    <tr style="border-top:1px solid #999">
      <td colspan="4"><strong>Total (excluding VAT)</strong></td>
      <td align="right"><strong>{escape(_money(quote.quote_value))}</strong></td>
    </tr>
  </tfoot>
</table>
<p>{escape(_lead_time_line(quote))}</p>
<p>{
        "This quotation is for machining only; material to be supplied by yourselves."
        if service_only
        else "Price includes material."
    }</p>
<p>This quotation is valid for 30 days. Please let us know if anything needs adjusting.</p>
<p>Kind regards</p>"""

    recipients = [enquiry.sender_email] if enquiry.sender_email else []
    if not recipients:
        raise ReplyError(f"Enquiry {enquiry.id} has no sender address to reply to.")

    return DraftReply(subject=subject, body_text=body_text, body_html=body_html, to=recipients)
