"""record forwarded RFQ origin

Revision ID: 17aef839394e
Revises: 621c22f3e39f
Create Date: 2026-09-04 14:50:44.112376
"""
from alembic import op
import sqlalchemy as sa


revision = '17aef839394e'
down_revision = '621c22f3e39f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forwarded_by', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('internal_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_column('internal_note')
        batch_op.drop_column('forwarded_by')

    # ### end Alembic commands ###
