"""initial schema

Revision ID: 621c22f3e39f
Revises: 
Create Date: 2026-09-03 17:00:26.584531
"""
from alembic import op
import sqlalchemy as sa


revision = '621c22f3e39f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('default_margin_pct', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('default_lead_days', sa.Integer(), nullable=False),
    sa.Column('is_material_supplied_default', sa.Boolean(), nullable=False),
    sa.Column('requires_cert', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_domain'), ['domain'], unique=False)

    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('outlook_message_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('customer_reference', sa.String(length=200), nullable=True),
    sa.Column('anchor_quote_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('turnaround_seconds', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anchor_quote_id'], ['quote.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outlook_message_id')
    )
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiry_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiry_status'), ['status'], unique=False)
        batch_op.create_index('ix_enquiry_status_received', ['status', 'received_at'], unique=False)

    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('material_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labour_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('margin_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quote_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=True),
    sa.Column('applied_rule_ids', sa.JSON(), nullable=True),
    sa.Column('min_value_applied', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.String(length=320), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen_snapshot', sa.JSON(), nullable=True),
    sa.Column('outlook_draft_id', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_id', 'version', name='uq_quote_enquiry_version')
    )
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_enquiry_id'), ['enquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_status'), ['status'], unique=False)

    op.create_table('quote_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=320), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note_kind', sa.String(length=32), nullable=True),
    sa.Column('adjustment_summary', sa.Text(), nullable=True),
    sa.Column('price_before', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('applied_rule_id', sa.Integer(), nullable=True),
    sa.Column('proposed_change', sa.JSON(), nullable=True),
    sa.Column('awaiting_answer', sa.Boolean(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applied_rule_id'], ['rules_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_note_quote_id'), ['quote_id'], unique=False)

    op.create_table('rate_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process', sa.String(length=32), nullable=False),
    sa.Column('machine_group', sa.String(length=120), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_table', schema=None) as batch_op:
        batch_op.create_index('ix_rate_lookup', ['process', 'machine_group', 'effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_table_process'), ['process'], unique=False)

    op.create_table('rules_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=60), nullable=False),
    sa.Column('trigger_description', sa.Text(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=16), nullable=False),
    sa.Column('adjustment_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('promoted_from_note_id', sa.Integer(), nullable=True),
    sa.Column('promoted_by', sa.String(length=320), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promoted_from_note_id'], ['quote_note.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_table_rule_key'), ['rule_key'], unique=False)

    op.create_table('stock_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=False),
    sa.Column('stock_form', sa.String(length=40), nullable=False),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kerf_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_size', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_size_spec'), ['spec'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('blob_uri', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('drawing_number', sa.String(length=120), nullable=True),
    sa.Column('revision', sa.String(length=40), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_drawing_number'), ['drawing_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_enquiry_id'), ['enquiry_id'], unique=False)

    op.create_table('quote_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('actual_production_mins', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    with op.batch_alter_table('quote_outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_outcome_result'), ['result'], unique=False)

    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('drawing_number', sa.String(length=120), nullable=True),
    sa.Column('revision', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_source', sa.String(length=20), nullable=True),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('heat_treatment', sa.String(length=200), nullable=True),
    sa.Column('surface_coat', sa.String(length=200), nullable=True),
    sa.Column('finish_spec', sa.String(length=200), nullable=True),
    sa.Column('envelope_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('envelope_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('envelope_z', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tightest_tolerance', sa.String(length=120), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('extraction_confidence', sa.JSON(), nullable=True),
    sa.Column('withheld_fields', sa.JSON(), nullable=True),
    sa.Column('process_mix', sa.JSON(), nullable=True),
    sa.Column('process_mix_constrained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_drawing_number'), ['drawing_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_enquiry_id'), ['enquiry_id'], unique=False)

    op.create_table('correction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('ai_value', sa.Text(), nullable=True),
    sa.Column('human_value', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('was_withheld', sa.Boolean(), nullable=False),
    sa.Column('corrected_by', sa.String(length=320), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_log_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_log_part_id'), ['part_id'], unique=False)

    op.create_table('flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('related_quote_id', sa.Integer(), nullable=True),
    sa.Column('related_enquiry_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=320), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_enquiry_id'], ['enquiry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_quote_id'], ['quote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flag_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_flag_enquiry_id'), ['enquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flag_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flag_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flag_severity'), ['severity'], unique=False)

    op.create_table('material_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('stock_form', sa.String(length=40), nullable=True),
    sa.Column('stock_size', sa.String(length=200), nullable=True),
    sa.Column('qty_required', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('blanks_per_unit_stock', sa.Integer(), nullable=True),
    sa.Column('utilisation_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_requirement_part_id'), ['part_id'], unique=False)

    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('op_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process', sa.String(length=32), nullable=False),
    sa.Column('set_time_mins', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('run_time_mins_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subcontract_unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('computed_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('time_source', sa.String(length=32), nullable=False),
    sa.Column('source_quote_id', sa.Integer(), nullable=True),
    sa.Column('rate_table_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_table_id'], ['rate_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_quote_id'], ['quote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'op_number', name='uq_operation_part_opnum')
    )
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_part_id'), ['part_id'], unique=False)

    op.create_table('quote_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('drawing_number', sa.String(length=120), nullable=True),
    sa.Column('revision', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_line_quote_id'), ['quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_line_quote_id'))

    op.drop_table('quote_line')
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_part_id'))

    op.drop_table('operation')
    with op.batch_alter_table('material_requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_requirement_part_id'))

    op.drop_table('material_requirement')
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flag_severity'))
        batch_op.drop_index(batch_op.f('ix_flag_quote_id'))
        batch_op.drop_index(batch_op.f('ix_flag_part_id'))
        batch_op.drop_index(batch_op.f('ix_flag_enquiry_id'))
        batch_op.drop_index(batch_op.f('ix_flag_dedupe_key'))

    op.drop_table('flag')
    with op.batch_alter_table('correction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_log_part_id'))
        batch_op.drop_index(batch_op.f('ix_correction_log_field_name'))

    op.drop_table('correction_log')
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_enquiry_id'))
        batch_op.drop_index(batch_op.f('ix_part_drawing_number'))

    op.drop_table('part')
    with op.batch_alter_table('quote_outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_outcome_result'))

    op.drop_table('quote_outcome')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_enquiry_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_drawing_number'))
        batch_op.drop_index(batch_op.f('ix_attachment_content_hash'))

    op.drop_table('attachment')
    with op.batch_alter_table('stock_size', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_size_spec'))

    op.drop_table('stock_size')
    with op.batch_alter_table('rules_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_table_rule_key'))

    op.drop_table('rules_table')
    with op.batch_alter_table('rate_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_table_process'))
        batch_op.drop_index('ix_rate_lookup')

    op.drop_table('rate_table')
    with op.batch_alter_table('quote_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_note_quote_id'))

    op.drop_table('quote_note')
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_status'))
        batch_op.drop_index(batch_op.f('ix_quote_enquiry_id'))

    op.drop_table('quote')
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_index('ix_enquiry_status_received')
        batch_op.drop_index(batch_op.f('ix_enquiry_status'))
        batch_op.drop_index(batch_op.f('ix_enquiry_customer_id'))

    op.drop_table('enquiry')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_domain'))

    op.drop_table('customer')
    # ### end Alembic commands ###
